### ISSUE TITLE
Default suggestions are a single string

### ISSUE THREAD

**Issue by inhumantsar** [careapp-inc/zxcvbn-dart#6]
Is this intentional? [Seems like there should be a comma here](https://github.com/careapp-inc/zxcvbn-dart/blob/ce6c4f5547f3694e173d0dd75e1fcdfa8cebc125/lib/src/feedback.dart#L13-L16).

**Comment by MichaelMarner** [comment]
Thanks for reporting. Yes, this is a bug, and is an artifact of porting from CoffeeScript, where the [comma is optional](https://coffeescript.org/#objects-and-arrays):

> When each property is listed on its own line, the commas are optional
